### PR TITLE
Examples: Get a complete project requirements tree

### PR DESCRIPTION
**Pull request by stanislaw**
Also provide convenience methods to access requirements-related entities:

1) Folders
2) Specs
3) Groups
4) Requirements

NOTE: This contribution is made on behalf of Reflex Aerospace GmbH, where I am employed as a software engineer.

### CODE REVIEW

**Comment by stanislaw** [comment]
@cauenapier, as discussed and promised in the support ticket `[VS-1017] Export from Valispace: How to export complete requirements information?`, here is how we made it working well enough for our needs.

[VS-1017]: https://valispace.atlassian.net/browse/VS-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cauenapier** [comment]
Hello @stanislaw , 
I'm sorry this repo and this PR have been neglected for a while. But I'll be pushing things forward here.

However, I've tested your example and it seems that it only works if all specs are in a folder and breaks if you ahve a spec in the root, since you are iterating first over folders.
Are you willing to review and modify the code?

**Comment by stanislaw** [comment]
Hi @cauenapier, thanks for coming back to me. I should be able to review this code within this week or next week. I will get back to this one.

**Comment by stanislaw** [comment]
One more heads up. I got blocked by work but I should be able to revisit this within this month definitely.

**Comment by stanislaw** [comment]
Hey @cauenapier ,

I have addressed your change, and everything seems to work on my end. The real project I have access to didn't have the top-level specifications, so I missed that case before. Now I have tested the new code using an artificial example, and the top-level specs are printed correctly.

Let me know if it works for you as well. 

Thank you.

**Pull request merged**
